name: AI News Daily Scheduler

on:
  schedule:
    # Every day at 9:00 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  run-ai-news:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      # Step 4: List installed packages (debug)
      - name: List installed packages
        run: python -m pip list

      # Step 5: Run AI News Scheduler
      - name: Run AI News Scheduler
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python ai_news_scheduler.py
