# .github/workflows/scheduler.yml
name: AI News Daily Scheduler

on:
  schedule:
    # Runs every day at 04:30 UTC (adjust as needed)
    - cron: "30 4 * * *"
  workflow_dispatch:

jobs:
  run-ai-news:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      # Step 5: List installed packages (debug)
      - name: List installed packages
        run: python -m pip list

      # Step 6: Run AI News Scheduler
      - name: Run AI News Scheduler
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python ai_news_scheduler.py
