name: AI News Scheduler

on:
  schedule:
    # Runs daily at 4:30 UTC (10:00 AM IST)
    - cron: "30 4 * * *"
  workflow_dispatch:

jobs:
  run-ai-news:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Upgrade pip and install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir -r requirements.txt

      # Step 4: Debug - verify moviepy installed
      - name: List installed packages
        run: python -m pip list

      # Step 5: Run the AI News Scheduler
      - name: Run AI News Scheduler
        run: python ai_news_scheduler.py
