name: AI News Daily Scheduler

on:
  schedule:
    - cron: "40 4 * * *"   # Runs every day at 04:40 UTC
  workflow_dispatch:

jobs:
  run-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      # FIX: Replaced shell here-document (<<EOF) with a robust multi-line execution.
      - name: Check Python Dependencies and FFmpeg Availability
        run: |
          python -c "
import cv2
import numpy
import requests
import subprocess
import importlib.metadata
from sys import exit

# Check gTTS version
try:
    gtts_version = importlib.metadata.version('gTTS')
except importlib.metadata.PackageNotFoundError:
    exit('gTTS not installed')

# Print versions
print(f'OpenCV {cv2.__version__}, NumPy {numpy.__version__}, gTTS {gtts_version}')

# Check FFmpeg
try:
    subprocess.run(['ffmpeg', '-version'], check=True, stdout=subprocess.DEVNULL)
except FileNotFoundError:
    exit('FFmpeg not found. Please ensure it is installed on the runner.')
"
      - name: Run AI News Scheduler
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python ai_news_scheduler.py
