name: AI News Daily Scheduler

on:
  schedule:
    - cron: "40 4 * * *"  # Every day at 04:40 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install gTTS==2.3.1 opencv-python==4.8.0.76 numpy requests

      - name: Check dependencies before running
        run: |
          python -c "import cv2, gtts, numpy, requests; import subprocess; subprocess.run(['ffmpeg', '-version'], check=True)"
      
      - name: Run AI News Scheduler
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python ai_news_scheduler.py
