name: AI News Scheduler

on:
  schedule:
    - cron: "30 4 * * *"  # every day at 04:30 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Dependency check
        run: |
          python -c "import cv2, numpy, gtts, requests; import subprocess; subprocess.run(['ffmpeg','-version'], check=True)"
        
      - name: Run AI News Scheduler
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python ai_news_scheduler.py
