name: AI News Daily Scheduler

# Run every day at 04:40 UTC (9:10 AM IST)
on:
  schedule:
    - cron: "40 4 * * *"
  workflow_dispatch:

jobs:
  run-ai-news:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # List installed packages (optional, for debug)
      - name: List installed packages
        run: python -m pip list

      # Run AI News Scheduler
      - name: Run AI News Scheduler
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python ai_news_scheduler.py
