name: AI News Scheduler

on:
  schedule:
    - cron: '30 9 * * *'  # Runs every day at 09:30 UTC
  workflow_dispatch:  # Manual trigger

jobs:
  run-scheduler:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install moviepy==2.1.1 gTTS==2.3.2 requests schedule beautifulsoup4 feedparser

      # List installed packages (optional, for debug)
      - name: List installed packages
        run: python -m pip list

      # Run AI News Scheduler
      - name: Run AI News Scheduler
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python ai_news_scheduler.py
