name: AI News Daily Scheduler

# Runs every day at 04:40 UTC (10:10 AM IST)
on:
  schedule:
    - cron: "40 4 * * *"
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # 3️⃣ Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 4️⃣ Install dependencies (fresh install)
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      # 5️⃣ Run the AI news scheduler script
      - name: Run AI News Scheduler
        run: python ai_news_scheduler.py

      # 6️⃣ Optional: Upload generated MP4 as artifact
      - name: Upload generated MP4
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: ai-news-video
          path: ./output/*.mp4
