name: AI News Scheduler

on:
  schedule:
    - cron: "30 4 * * *"  # Daily at 04:30 UTC
  workflow_dispatch:       # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Test MoviePy MP4 generation
      - name: Test MP4 generation
        run: |
          python3 -c "from moviepy.editor import TextClip; TextClip('Test', fontsize=50, color='white').write_videofile('test.mp4', fps=24, codec='libx264')"

      # Run AI News Scheduler
      - name: Run AI News Scheduler
        run: python3 ai_news_scheduler.py
